//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppGestionGarageManagement.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Voiture", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGestionGarage.Model")]
    [System.SerializableAttribute()]
    public partial class Voiture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroChassisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marque {
            get {
                return this.MarqueField;
            }
            set {
                if ((object.ReferenceEquals(this.MarqueField, value) != true)) {
                    this.MarqueField = value;
                    this.RaisePropertyChanged("Marque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricule {
            get {
                return this.MatriculeField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculeField, value) != true)) {
                    this.MatriculeField = value;
                    this.RaisePropertyChanged("Matricule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroChassis {
            get {
                return this.NumeroChassisField;
            }
            set {
                if ((this.NumeroChassisField.Equals(value) != true)) {
                    this.NumeroChassisField = value;
                    this.RaisePropertyChanged("NumeroChassis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutVoitre", ReplyAction="http://tempuri.org/IService1/AjoutVoitreResponse")]
        int AjoutVoitre(WpfAppGestionGarageManagement.ServiceReference1.Voiture voiture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AjoutVoitre", ReplyAction="http://tempuri.org/IService1/AjoutVoitreResponse")]
        System.Threading.Tasks.Task<int> AjoutVoitreAsync(WpfAppGestionGarageManagement.ServiceReference1.Voiture voiture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuppVoitureById", ReplyAction="http://tempuri.org/IService1/SuppVoitureByIdResponse")]
        bool SuppVoitureById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SuppVoitureById", ReplyAction="http://tempuri.org/IService1/SuppVoitureByIdResponse")]
        System.Threading.Tasks.Task<bool> SuppVoitureByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifVoiture", ReplyAction="http://tempuri.org/IService1/ModifVoitureResponse")]
        bool ModifVoiture(WpfAppGestionGarageManagement.ServiceReference1.Voiture voiture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModifVoiture", ReplyAction="http://tempuri.org/IService1/ModifVoitureResponse")]
        System.Threading.Tasks.Task<bool> ModifVoitureAsync(WpfAppGestionGarageManagement.ServiceReference1.Voiture voiture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListVoitures", ReplyAction="http://tempuri.org/IService1/ListVoituresResponse")]
        WpfAppGestionGarageManagement.ServiceReference1.Voiture[] ListVoitures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListVoitures", ReplyAction="http://tempuri.org/IService1/ListVoituresResponse")]
        System.Threading.Tasks.Task<WpfAppGestionGarageManagement.ServiceReference1.Voiture[]> ListVoituresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RechercheParCritere", ReplyAction="http://tempuri.org/IService1/RechercheParCritereResponse")]
        WpfAppGestionGarageManagement.ServiceReference1.Voiture[] RechercheParCritere(string critere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RechercheParCritere", ReplyAction="http://tempuri.org/IService1/RechercheParCritereResponse")]
        System.Threading.Tasks.Task<WpfAppGestionGarageManagement.ServiceReference1.Voiture[]> RechercheParCritereAsync(string critere);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfAppGestionGarageManagement.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfAppGestionGarageManagement.ServiceReference1.IService1>, WpfAppGestionGarageManagement.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AjoutVoitre(WpfAppGestionGarageManagement.ServiceReference1.Voiture voiture) {
            return base.Channel.AjoutVoitre(voiture);
        }
        
        public System.Threading.Tasks.Task<int> AjoutVoitreAsync(WpfAppGestionGarageManagement.ServiceReference1.Voiture voiture) {
            return base.Channel.AjoutVoitreAsync(voiture);
        }
        
        public bool SuppVoitureById(int id) {
            return base.Channel.SuppVoitureById(id);
        }
        
        public System.Threading.Tasks.Task<bool> SuppVoitureByIdAsync(int id) {
            return base.Channel.SuppVoitureByIdAsync(id);
        }
        
        public bool ModifVoiture(WpfAppGestionGarageManagement.ServiceReference1.Voiture voiture) {
            return base.Channel.ModifVoiture(voiture);
        }
        
        public System.Threading.Tasks.Task<bool> ModifVoitureAsync(WpfAppGestionGarageManagement.ServiceReference1.Voiture voiture) {
            return base.Channel.ModifVoitureAsync(voiture);
        }
        
        public WpfAppGestionGarageManagement.ServiceReference1.Voiture[] ListVoitures() {
            return base.Channel.ListVoitures();
        }
        
        public System.Threading.Tasks.Task<WpfAppGestionGarageManagement.ServiceReference1.Voiture[]> ListVoituresAsync() {
            return base.Channel.ListVoituresAsync();
        }
        
        public WpfAppGestionGarageManagement.ServiceReference1.Voiture[] RechercheParCritere(string critere) {
            return base.Channel.RechercheParCritere(critere);
        }
        
        public System.Threading.Tasks.Task<WpfAppGestionGarageManagement.ServiceReference1.Voiture[]> RechercheParCritereAsync(string critere) {
            return base.Channel.RechercheParCritereAsync(critere);
        }
    }
}
