// <auto-generated />
namespace WebApplicationASPWebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Annotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Annotation));
        
        string IMigrationMetadata.Id
        {
            get { return "202007100956396_Annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
