//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppClientGarageWS.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Voiture", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceGarage.Model")]
    [System.SerializableAttribute()]
    public partial class Voiture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChassisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Chassis {
            get {
                return this.ChassisField;
            }
            set {
                if ((this.ChassisField.Equals(value) != true)) {
                    this.ChassisField = value;
                    this.RaisePropertyChanged("Chassis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marque {
            get {
                return this.MarqueField;
            }
            set {
                if ((object.ReferenceEquals(this.MarqueField, value) != true)) {
                    this.MarqueField = value;
                    this.RaisePropertyChanged("Marque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricule {
            get {
                return this.MatriculeField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculeField, value) != true)) {
                    this.MatriculeField = value;
                    this.RaisePropertyChanged("Matricule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWSGarage")]
    public interface IWSGarage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/AjoutVoiture", ReplyAction="http://tempuri.org/IWSGarage/AjoutVoitureResponse")]
        int AjoutVoiture(WpfAppClientGarageWS.ServiceReference1.Voiture voiture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/AjoutVoiture", ReplyAction="http://tempuri.org/IWSGarage/AjoutVoitureResponse")]
        System.Threading.Tasks.Task<int> AjoutVoitureAsync(WpfAppClientGarageWS.ServiceReference1.Voiture voiture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/ModifVoiture", ReplyAction="http://tempuri.org/IWSGarage/ModifVoitureResponse")]
        bool ModifVoiture(WpfAppClientGarageWS.ServiceReference1.Voiture voiture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/ModifVoiture", ReplyAction="http://tempuri.org/IWSGarage/ModifVoitureResponse")]
        System.Threading.Tasks.Task<bool> ModifVoitureAsync(WpfAppClientGarageWS.ServiceReference1.Voiture voiture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/SuppVoitureById", ReplyAction="http://tempuri.org/IWSGarage/SuppVoitureByIdResponse")]
        bool SuppVoitureById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/SuppVoitureById", ReplyAction="http://tempuri.org/IWSGarage/SuppVoitureByIdResponse")]
        System.Threading.Tasks.Task<bool> SuppVoitureByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/GetVoitures", ReplyAction="http://tempuri.org/IWSGarage/GetVoituresResponse")]
        WpfAppClientGarageWS.ServiceReference1.Voiture[] GetVoitures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/GetVoitures", ReplyAction="http://tempuri.org/IWSGarage/GetVoituresResponse")]
        System.Threading.Tasks.Task<WpfAppClientGarageWS.ServiceReference1.Voiture[]> GetVoituresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/RechercheParCritere", ReplyAction="http://tempuri.org/IWSGarage/RechercheParCritereResponse")]
        WpfAppClientGarageWS.ServiceReference1.Voiture[] RechercheParCritere(string critere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSGarage/RechercheParCritere", ReplyAction="http://tempuri.org/IWSGarage/RechercheParCritereResponse")]
        System.Threading.Tasks.Task<WpfAppClientGarageWS.ServiceReference1.Voiture[]> RechercheParCritereAsync(string critere);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSGarageChannel : WpfAppClientGarageWS.ServiceReference1.IWSGarage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSGarageClient : System.ServiceModel.ClientBase<WpfAppClientGarageWS.ServiceReference1.IWSGarage>, WpfAppClientGarageWS.ServiceReference1.IWSGarage {
        
        public WSGarageClient() {
        }
        
        public WSGarageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSGarageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSGarageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSGarageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AjoutVoiture(WpfAppClientGarageWS.ServiceReference1.Voiture voiture) {
            return base.Channel.AjoutVoiture(voiture);
        }
        
        public System.Threading.Tasks.Task<int> AjoutVoitureAsync(WpfAppClientGarageWS.ServiceReference1.Voiture voiture) {
            return base.Channel.AjoutVoitureAsync(voiture);
        }
        
        public bool ModifVoiture(WpfAppClientGarageWS.ServiceReference1.Voiture voiture) {
            return base.Channel.ModifVoiture(voiture);
        }
        
        public System.Threading.Tasks.Task<bool> ModifVoitureAsync(WpfAppClientGarageWS.ServiceReference1.Voiture voiture) {
            return base.Channel.ModifVoitureAsync(voiture);
        }
        
        public bool SuppVoitureById(int id) {
            return base.Channel.SuppVoitureById(id);
        }
        
        public System.Threading.Tasks.Task<bool> SuppVoitureByIdAsync(int id) {
            return base.Channel.SuppVoitureByIdAsync(id);
        }
        
        public WpfAppClientGarageWS.ServiceReference1.Voiture[] GetVoitures() {
            return base.Channel.GetVoitures();
        }
        
        public System.Threading.Tasks.Task<WpfAppClientGarageWS.ServiceReference1.Voiture[]> GetVoituresAsync() {
            return base.Channel.GetVoituresAsync();
        }
        
        public WpfAppClientGarageWS.ServiceReference1.Voiture[] RechercheParCritere(string critere) {
            return base.Channel.RechercheParCritere(critere);
        }
        
        public System.Threading.Tasks.Task<WpfAppClientGarageWS.ServiceReference1.Voiture[]> RechercheParCritereAsync(string critere) {
            return base.Channel.RechercheParCritereAsync(critere);
        }
    }
}
